---
title: "Recommended Exercise 2 in Statistical Linear Models, Spring 2021"
author: "alexaoh"
date: "22.01.2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, comment = "#>")
```

# Problem 1 \hspace{3mm} Principal Component Analysis (PCA)
```{r}
#str(USArrests) # Data set included in R. 

# a) Find loadings/rotations of the PC's. 
pc <- prcomp(USArrests, scale = T)
pc$rotation # Loadings via prcomp() function

# Loadings via finding the eigenvalues of correlation 
# (since we want scaled variables) matrix of the data.
eigen(cor(USArrests))$vectors 

# b) Find sample variance of the PC's.
pc$sdev^2 # Sample variances using prcomp() function.
eigen(cor(USArrests))$values # Sample variances via correlation matrix. 

# c) Find the scores and check that the scores for Alabama are indeed
#    the linear combinations of the data for Alabama with the loadings 
#    as coefficients. 
pc$x # Scores. 
pc$x[1,] # Scores of Alabama.
# The calculations below give the same results. 
t(pc$rotation) %*% t(scale(USArrests))[,"Alabama"]
t(pc$rotation) %*% t(data.matrix(scale(USArrests)))[,1]

# d) Biplot of the two first PC's.
plot(pc$x[,1],pc$x[,2],type="n")
text(pc$x[,1],pc$x[,2],rownames(USArrests),cex=0.6)
biplot(pc, scale = 0,cex=0.4)
plot(scale(USArrests)[, 2], scale(USArrests)[, 4])
abline(0, pc$rotation[2, 1] / pc$rotation[4, 1], col = "red")
biplot(pc, choices = c(1,3), scale = 0,cex=0.4)
# e) 
summary(pc) 
plot(pc) # Screeplot.
# It is apparent that we need 2 PC's to capture more than 80% of the variability. 
```
--- 
### f) All the tasks from above repeated, but without scaling.
```{r}
# a) Find loadings/rotations of the PC's. 
pc.noscale <- prcomp(USArrests, scale = F)
pc.noscale$rotation # Loadings via prcomp() function

# Loadings via finding the eigenvalues of correlation 
# (since we want scaled variables) matrix of the data.
eigen(cov(USArrests))$vectors 

# b) Find sample variance of the PC's.
pc.noscale$sdev^2 # Sample variances using prcomp() function.
eigen(cov(USArrests))$values # Sample variances via correlation matrix. 

# c) Find the scores and check that the scores for Alabama are indeed
#    the linear combinations of the data for Alabama with the loadings 
#    as coefficients. 
pc.noscale$x # Scores. 
pc.noscale$x[1,] # Scores of Alabama.
# The calculations below give the same results. 
t(pc.noscale$rotation) %*% data.matrix(USArrests)[1,]

# d) Biplot of the two first PC's.
biplot(pc.noscale, scale = 0,cex=0.4)

# e) 
summary(pc.noscale) 
# It is apparent that the components with the highest variance dominate (PC1 most significantly).

cov(USArrests) # Here we see which of the variables have the highest variables. 
```

***

# Problem 4 \hspace{3mm} Normal and chi-squared distributions in R

```{r}
?rnorm
?pchisq
```

## b) 
Make a plot of the standard normal pdf.
```{r}
left.endpoint <- -3
right.endpoint <- 3
x <- seq(left.endpoint, right.endpoint, by = 0.01)
y <- dnorm(x)

plot(x,y, type = "l", lwd = 0.8, xlim = c(left.endpoint+0.5, right.endpoint-0.5))
# Kan heller skrive:
# plot(dnorm, left.endpoint, right.endoint)
abline(v = c(qnorm(0.05), qnorm(0.95)), col = "red")

# Coloring in the tails next.
left.x <- seq(left.endpoint, qnorm(0.05), by = 0.01)
right.x <- seq(qnorm(0.95), right.endpoint, by = 0.01)
left.y <- dnorm(left.x)
right.y <- dnorm(right.x)
polygon(x = c(qnorm(0.95), right.x, right.endpoint) , y = c(0, right.y, 0), col = "skyblue")
polygon(x = c(left.endpoint, left.x, qnorm(0.05)) , y = c(0, left.y, 0), col = "skyblue")
```

## c) 

```{r}
data <- rnorm(10000)^2

hist(data, nclass = 100, freq = F, main = "Std Gaussian^2 and Chisquared df = 1")

# Add chi-squared.
plot(function(x) dchisq(x, df = 1), from = min(data), to = max(data), add = TRUE, col = "red")

# Add quantiles. 
abline(v = c(qchisq(0.1, df = 1), qchisq(0.9, df = 1)), col = c("green", "blue"))
```


